<? include "header.phtml"; ?>
<h1>
	<?=$this->escape($this->title);?>
</h1>
<form method='post' action='<?=$this->escape($this->action);?>'>
	<div>
		<div>
			<? if ($this->erro):?>
				<h4>Usu‡rio ou senha inv‡lidos!</h4><br>
			<? endif; ?>
		</div>
		<div>
			<?=$this->escape($this->usuario);?><br>
			<input type='text' name='usuario'><br>
		</div>
		<div>
			<?=$this->escape($this->senha);?><br>
			<input type='password' name='senha'><br>
		</div>
	</div>
	<input type='submit' name='login' value='Login'>
</form>
<? include "footer.phtml"; ?>