<? include "header.phtml"; ?>
<h1>
	<?=$this->escape($this->title);?>
</h1>
<form method='post' action='<?=$this->escape($this->action);?>'>
	<table>
		<tr>
			<td><?=$this->escape($this->usuario);?></td>
			<td><input type='text' name='usuario'></td>
		</tr>
		<tr>
			<td><?=$this->escape($this->senha);?></td>
			<td><input type='password' name='senha'></td>
		</tr>
	</table>
	<input type='submit' name='login' value='Login'>
</form>
<? include "footer.phtml"; ?>